DROP TABLE IF EXISTS user;

CREATE TABLE user
(
  id BIGINT(20) NOT NULL COMMENT '主键',
  name VARCHAR(50) NULL DEFAULT NULL COMMENT '姓名',
  phone VARCHAR(256) NULL DEFAULT NULL COMMENT '手机号',
  PRIMARY KEY (id)
);